sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t akhil211/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true akhil211/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  env: docker-react-env
  app: docker-react
  bucket_name: "elasticbeanstalk-us-east-1-402359913724"
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
